#!/bin/sh
if ! brew ls --versions yarn > /dev/null; then
    brew install yarn
fi
yarn install
mkdir -p explain-outputs
node generate.js -t explain-template.png -o explain-outputs inputs/*
mkdir -p rate-outputs
node generate.js -t rate-template.png -o rate-outputs inputs/*
